/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWorkspaceIdRouteImport } from './routes/_app/$workspaceId'
import { Route as ExtensionLinkRouteImport } from './routes/extension/link'
import { Route as AppWorkspaceIdIndexRouteImport } from './routes/_app/$workspaceId/index'
import { Route as AppOnboardingIndexRouteImport } from './routes/_app/onboarding/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppWorkspaceIdVaultIndexRouteImport } from './routes/_app/$workspaceId/vault/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceIdRoute = AppWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const ExtensionLinkRoute = ExtensionLinkRouteImport.update({
  id: '/extension/link',
  path: '/extension/link',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceIdIndexRoute = AppWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceIdRoute,
} as any)
const AppOnboardingIndexRoute = AppOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceIdVaultIndexRoute =
  AppWorkspaceIdVaultIndexRouteImport.update({
    id: '/vault/',
    path: '/vault/',
    getParentRoute: () => AppWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$workspaceId': typeof AppWorkspaceIdRouteWithChildren
  '/extension/link': typeof ExtensionLinkRoute
  '/$workspaceId/': typeof AppWorkspaceIdIndexRoute
  '/onboarding/': typeof AppOnboardingIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/$workspaceId/vault/': typeof AppWorkspaceIdVaultIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/extension/link': typeof ExtensionLinkRoute
  '/': typeof AppIndexRoute
  '/$workspaceId': typeof AppWorkspaceIdIndexRoute
  '/onboarding': typeof AppOnboardingIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/$workspaceId/vault': typeof AppWorkspaceIdVaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$workspaceId': typeof AppWorkspaceIdRouteWithChildren
  '/extension/link': typeof ExtensionLinkRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$workspaceId/': typeof AppWorkspaceIdIndexRoute
  '/_app/onboarding/': typeof AppOnboardingIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/$workspaceId/vault/': typeof AppWorkspaceIdVaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$workspaceId'
    | '/extension/link'
    | '/$workspaceId/'
    | '/onboarding/'
    | '/settings/'
    | '/$workspaceId/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/extension/link'
    | '/'
    | '/$workspaceId'
    | '/onboarding'
    | '/settings'
    | '/$workspaceId/vault'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$workspaceId'
    | '/extension/link'
    | '/_app/'
    | '/_app/$workspaceId/'
    | '/_app/onboarding/'
    | '/_app/settings/'
    | '/_app/$workspaceId/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ExtensionLinkRoute: typeof ExtensionLinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$workspaceId': {
      id: '/_app/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/extension/link': {
      id: '/extension/link'
      path: '/extension/link'
      fullPath: '/extension/link'
      preLoaderRoute: typeof ExtensionLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$workspaceId/': {
      id: '/_app/$workspaceId/'
      path: '/'
      fullPath: '/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWorkspaceIdRoute
    }
    '/_app/onboarding/': {
      id: '/_app/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AppOnboardingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$workspaceId/vault/': {
      id: '/_app/$workspaceId/vault/'
      path: '/vault'
      fullPath: '/$workspaceId/vault/'
      preLoaderRoute: typeof AppWorkspaceIdVaultIndexRouteImport
      parentRoute: typeof AppWorkspaceIdRoute
    }
  }
}

interface AppWorkspaceIdRouteChildren {
  AppWorkspaceIdIndexRoute: typeof AppWorkspaceIdIndexRoute
  AppWorkspaceIdVaultIndexRoute: typeof AppWorkspaceIdVaultIndexRoute
}

const AppWorkspaceIdRouteChildren: AppWorkspaceIdRouteChildren = {
  AppWorkspaceIdIndexRoute: AppWorkspaceIdIndexRoute,
  AppWorkspaceIdVaultIndexRoute: AppWorkspaceIdVaultIndexRoute,
}

const AppWorkspaceIdRouteWithChildren = AppWorkspaceIdRoute._addFileChildren(
  AppWorkspaceIdRouteChildren,
)

interface AppRouteChildren {
  AppWorkspaceIdRoute: typeof AppWorkspaceIdRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceIdRoute: AppWorkspaceIdRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ExtensionLinkRoute: ExtensionLinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
