/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWorkspaceIdRouteImport } from './routes/_app/$workspaceId'
import { Route as ExtensionLinkRouteImport } from './routes/extension/link'
import { Route as AppWorkspaceIdIndexRouteImport } from './routes/_app/$workspaceId/index'
import { Route as AppFeedsIndexRouteImport } from './routes/_app/feeds/index'
import { Route as AppInboxIndexRouteImport } from './routes/_app/inbox/index'
import { Route as AppOnboardingIndexRouteImport } from './routes/_app/onboarding/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppFeedsFeedIdIndexRouteImport } from './routes/_app/feeds/$feedId/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceIdRoute = AppWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const ExtensionLinkRoute = ExtensionLinkRouteImport.update({
  id: '/extension/link',
  path: '/extension/link',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceIdIndexRoute = AppWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceIdRoute,
} as any)
const AppFeedsIndexRoute = AppFeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingIndexRoute = AppOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedsFeedIdIndexRoute = AppFeedsFeedIdIndexRouteImport.update({
  id: '/feeds/$feedId/',
  path: '/feeds/$feedId/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$workspaceId': typeof AppWorkspaceIdRouteWithChildren
  '/extension/link': typeof ExtensionLinkRoute
  '/$workspaceId/': typeof AppWorkspaceIdIndexRoute
  '/feeds/': typeof AppFeedsIndexRoute
  '/inbox/': typeof AppInboxIndexRoute
  '/onboarding/': typeof AppOnboardingIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/feeds/$feedId/': typeof AppFeedsFeedIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/extension/link': typeof ExtensionLinkRoute
  '/': typeof AppIndexRoute
  '/$workspaceId': typeof AppWorkspaceIdIndexRoute
  '/feeds': typeof AppFeedsIndexRoute
  '/inbox': typeof AppInboxIndexRoute
  '/onboarding': typeof AppOnboardingIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/feeds/$feedId': typeof AppFeedsFeedIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$workspaceId': typeof AppWorkspaceIdRouteWithChildren
  '/extension/link': typeof ExtensionLinkRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$workspaceId/': typeof AppWorkspaceIdIndexRoute
  '/_app/feeds/': typeof AppFeedsIndexRoute
  '/_app/inbox/': typeof AppInboxIndexRoute
  '/_app/onboarding/': typeof AppOnboardingIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/feeds/$feedId/': typeof AppFeedsFeedIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$workspaceId'
    | '/extension/link'
    | '/$workspaceId/'
    | '/feeds/'
    | '/inbox/'
    | '/onboarding/'
    | '/settings/'
    | '/feeds/$feedId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/extension/link'
    | '/'
    | '/$workspaceId'
    | '/feeds'
    | '/inbox'
    | '/onboarding'
    | '/settings'
    | '/feeds/$feedId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$workspaceId'
    | '/extension/link'
    | '/_app/'
    | '/_app/$workspaceId/'
    | '/_app/feeds/'
    | '/_app/inbox/'
    | '/_app/onboarding/'
    | '/_app/settings/'
    | '/_app/feeds/$feedId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ExtensionLinkRoute: typeof ExtensionLinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$workspaceId': {
      id: '/_app/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/extension/link': {
      id: '/extension/link'
      path: '/extension/link'
      fullPath: '/extension/link'
      preLoaderRoute: typeof ExtensionLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$workspaceId/': {
      id: '/_app/$workspaceId/'
      path: '/'
      fullPath: '/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWorkspaceIdRoute
    }
    '/_app/feeds/': {
      id: '/_app/feeds/'
      path: '/feeds'
      fullPath: '/feeds/'
      preLoaderRoute: typeof AppFeedsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/': {
      id: '/_app/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AppOnboardingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feeds/$feedId/': {
      id: '/_app/feeds/$feedId/'
      path: '/feeds/$feedId'
      fullPath: '/feeds/$feedId/'
      preLoaderRoute: typeof AppFeedsFeedIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppWorkspaceIdRouteChildren {
  AppWorkspaceIdIndexRoute: typeof AppWorkspaceIdIndexRoute
}

const AppWorkspaceIdRouteChildren: AppWorkspaceIdRouteChildren = {
  AppWorkspaceIdIndexRoute: AppWorkspaceIdIndexRoute,
}

const AppWorkspaceIdRouteWithChildren = AppWorkspaceIdRoute._addFileChildren(
  AppWorkspaceIdRouteChildren,
)

interface AppRouteChildren {
  AppWorkspaceIdRoute: typeof AppWorkspaceIdRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppFeedsIndexRoute: typeof AppFeedsIndexRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppFeedsFeedIdIndexRoute: typeof AppFeedsFeedIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceIdRoute: AppWorkspaceIdRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppFeedsIndexRoute: AppFeedsIndexRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppFeedsFeedIdIndexRoute: AppFeedsFeedIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ExtensionLinkRoute: ExtensionLinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
